### ISSUE TITLE
It's impossible to update the service without restarting the server

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server-tools#12]
I have an idea for how this could be done. Instead of killing the DD process, we merely let it go and reattach to it on service startup.

- Attachment can be done at any startup if there is a DD process running in the context of the service account
- This does mean we will miss any relays sent to the service during the operation. Maybe require an ACK from the service for each?
- Having this all be initiated by an installation is the problem we have a couple of options for notifying the server

1. Call a function through the interface: Ideal, but may be too dependency heavy
2. Write to a file the service looks out for: Too hacky imo
3. Use a native service command: https://msdn.microsoft.com/en-us/library/system.serviceprocess.servicebase.oncustomcommand(v=vs.110).aspx
4. Write an immutable base executable that loads a dll with the code and switch it out on updates: May be too complex

The hard part about any of the is getting our installer to dance to this tune

**Comment by MrStonedOne** [comment]
we could load a dll dm side, and use it and named pipes and/or shared memory, and have it queue nudges while the service is afk.

We could load a temp program in userland to receive the nudge, then reply them at the end.

We could have the service always start a seperate binary for receiving the nudge, and have it handle queuing. You wouldn't be able to update this without issues, but being smaller, the nudge ferry process could be easily restarted and we just accept the minor race condition (maybe have the service wait for world restart to restart it, thats 5 to 15 seconds of time that the server will not be able to send any nudges.

**Comment by MrStonedOne** [comment]
We could also just stage the service using the same A/B system

**Comment by MrStonedOne** [comment]
We could also just stage the service using the same A/B system.

Then a normal service restart would solve it, and just make the service not kill dd on service restarts. (iirc a service can tell the difference between a stop and a restart)
