### ISSUE TITLE
Discord Bot spam connecting

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation-server-tools#15]
Bot Token Reset Due to Potential Abuse

It appears your bot, MimeBot, has connected to Discord more than 1000 times within a short time period. Since this kind of behavior is usually a result of a bug we have gone ahead and reset your bot's token.

**Comment by Cyberboss** [comment]
Is that message sent via e-mail?

**Comment by Cyberboss** [comment]
That updated version I gave you should have this fixed. If it hasn't let me know
