### ISSUE TITLE
Symlink targeting is not 100% reliable

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server-tools#42]
See comments in #40

**Comment by MrStonedOne** [comment]
How are you doing it?

**Comment by JamieH** [comment]
Why is TGS3 trying to make symlinks on the live server folder? I think that is what's breaking it, the update is nuking the folder and then DD remakes data folder because it needs it, hence the symlink can't be made.

**Comment by Cyberboss** [comment]
This is the code that's supposed to return the path to the game folder which does not have the game running https://github.com/tgstation/tgstation-server-tools/blob/master/TGServerService/Compiler.cs#L223

**Comment by MrStonedOne** [comment]
So it looks like the issue might be staged but unapplied changes, if you run update, and run some other change before a round restart, it might get confused and try to update to the folder the server is currently using, or if you account for that, but don't revert the staging, it could happen if the round restarts while the update operation is taking place.

**Comment by MrStonedOne** [comment]
These were all edge cases I had to handle in tgs2

**Comment by MrStonedOne** [comment]
These were all edge cases I had to handle in tgs2's bin/findab.bat

**Comment by MrStonedOne** [comment]
Also, dd does like to aggressively recreate folders to files it has open, one thing your stuff should expect to have to do is clear out those folders while its moving symlinks around, or expect normal folders/files to appear where symlinks used to exist, and handle them gracefully (I intentionally deleted the old symlink in a way that supported this)

Another solution is to suspend the dd process for the short time it takes to re-target the symlink. I doubt it would be a noticeable bit of lag.
