### ISSUE TITLE
Commands to run on certain actions

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server-tools#48]
I'm in the middle of building a docker container framework that can be used to host "edge" cdn byond servers that send the user the resources and then send them on to the real server.

The last step would be some way to know when the server's rsc has changed and trigger a rebuild of the docker image (I'll have it grab the rsc via the smb share that already exists for the game folder, that part isn't hard)

So I was thinking, it would be handy to create events that ran things.

You could do this the user friendly way and make an interface for the different types of events (restart, round end, crash, update, compile, etc), or you can just push unique event ids in windows event viewer and i can just make scheduled tasks based off of them.

Just try to be as granular as sanely possible and very particular in your documentation about what events trigger when.

**Comment by JamieH** [comment]
+1 for unique event IDs in Windows Event Viewer, that's 100% the best solution I can think off.
