### ISSUE TITLE
RSC corruption likely caused by an old rsc sticking around in the staging folder.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server-tools#64]
If there is a rsc in the folder, byond will try to re-use it, and even use it for resources not in the actual project folder.

This (feature) of byond is horribly bugged, random bits of old versions of now not used files will get interspaced where nulls or rsc metadata should be.

Example:

`Ó....x">Photocopied papers will now retain their stamps</li>....` (. = unprintable character)
The Ó is the exact spot the last file ended (an ogg) at this point, there should be 18 bytes of meta data, followed by 4 bytes of payload size, a null terminated file name string (not part of the payload size), and the payload

Instead we have a random changelog entry.

This is a real example, from hippie.

tgs2 deleted the old staging folder every time before copying over from the repo to prevent things like this (and prevent now deleted files sticking around)

**Comment by Cyberboss** [comment]
TGS3 also deletes the folder, hmmm
